swap = {
    "aa": ["aa, ""ea", "ee", "ia", "oa", "ua"],
    "ae": ["ae", "ai", "ao", "ia", "oa", "ua"],
    "ah": ["ah", "ea", "eh"],
    "ao": ["ao", "eo", "io", "ao"],
    "aw": ["aw", "av"],
    "ax": ["az", "an", "ax", "as"],
    "ay": ["ay", "ai", "ae"],
    "b": ["b", "v", "r", "c"],
    "ch": ["sh", "ch", "nh", "dh"],
    "d": ["d", "v", "h", "c"],
    "dh": ["dh", "nh", "rh"],
    "ea": ["ea", "ia", "oa", "ua"],
    "eh": ["eh", "ih", "oh", "uh"],
    "er": ["er", "en", "ar", "an"],
    "f": ["f", "s", "h"],
    "g": ["g", "b", "v", "d", "c"],
    "hh": ["hh"],
    "ia": ["ia", "oa", "ua"],
    "ih": ["ih", "oh", "uh", "ah"],
    "iy": ["iy", "ie", "ia", "ae"],
    "jh": ["jh", "dh", "vh", "sh"],
    "k": ["k", "d", "v", "c"],
    "l": ["l", "m", "n", "r"],
    "m": ["m", "n", "r", "v"],
    "n": ["n", "m", "r", "v", "h"],
    "ng": ["ng", "rg", "vg"],
    "oh": ["oh", "oa", "ua"],
    "ow": ["ow", "ov", "oh"],
    "oy": ["oy", "uy", "ua"],
    "p": ["p", "v", "c"],
    "r": ["r", "f", "s", "d"],
    "s": ["s", "v", "t", "g"],
    "sh": ["sh", "vh", "th"],
    "t": ["t", "v", "b", "c"],
    "th": ["th", "vh", "sh"],
    "ua": ["ua", "ia", "oa", "ea"],
    "uh": ["uh", "ul", "ua", "oa", "ia"],
    "uw": ["uw", "uv", "ov", "aw", "ew"],
    "v": ["v", "g", "t"],
    "w": ["w"],
    "y": ["y", "e", "a"],
    "z": ["z", "s", "v"],
    "zh": ["sh", "zh", "vh"],
}